//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AdanaLaboratuvarEntegreServisi.ws_AdanaLabYeniEntegre {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EntegreLBYSLabServiceSoap", Namespace="http://www.esy.com.tr/")]
    public partial class EntegreLBYSLabService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AktifTestlerOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestEkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestGuncelleOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarkodSonucBilgisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TCSonucBilgisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarkodSilOperationCompleted;
        
        private System.Threading.SendOrPostCallback DuyurulariGetirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EntegreLBYSLabService() {
            this.Url = global::AdanaLaboratuvarEntegreServisi.Properties.Settings.Default.AdanaLaboratuvarEntegreServisi_ws_AdanaLabYeniEntegre_EntegreLBYSLabService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AktifTestlerCompletedEventHandler AktifTestlerCompleted;
        
        /// <remarks/>
        public event TestEkleCompletedEventHandler TestEkleCompleted;
        
        /// <remarks/>
        public event TestGuncelleCompletedEventHandler TestGuncelleCompleted;
        
        /// <remarks/>
        public event BarkodSonucBilgisiCompletedEventHandler BarkodSonucBilgisiCompleted;
        
        /// <remarks/>
        public event TCSonucBilgisiCompletedEventHandler TCSonucBilgisiCompleted;
        
        /// <remarks/>
        public event BarkodSilCompletedEventHandler BarkodSilCompleted;
        
        /// <remarks/>
        public event DuyurulariGetirCompletedEventHandler DuyurulariGetirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/AktifTestler", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AktifTest[] AktifTestler(string Kadi, string Ksifre) {
            object[] results = this.Invoke("AktifTestler", new object[] {
                        Kadi,
                        Ksifre});
            return ((AktifTest[])(results[0]));
        }
        
        /// <remarks/>
        public void AktifTestlerAsync(string Kadi, string Ksifre) {
            this.AktifTestlerAsync(Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void AktifTestlerAsync(string Kadi, string Ksifre, object userState) {
            if ((this.AktifTestlerOperationCompleted == null)) {
                this.AktifTestlerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAktifTestlerOperationCompleted);
            }
            this.InvokeAsync("AktifTestler", new object[] {
                        Kadi,
                        Ksifre}, this.AktifTestlerOperationCompleted, userState);
        }
        
        private void OnAktifTestlerOperationCompleted(object arg) {
            if ((this.AktifTestlerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AktifTestlerCompleted(this, new AktifTestlerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/TestEkle", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TestEkleSonuc[] TestEkle(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string ADI, string SOYADI, string CINSIYET, System.DateTime DTARIH, string ONTANI, int[] Test) {
            object[] results = this.Invoke("TestEkle", new object[] {
                        Kadi,
                        Ksifre,
                        BARKOD,
                        TCKIMLIK,
                        ADI,
                        SOYADI,
                        CINSIYET,
                        DTARIH,
                        ONTANI,
                        Test});
            return ((TestEkleSonuc[])(results[0]));
        }
        
        /// <remarks/>
        public void TestEkleAsync(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string ADI, string SOYADI, string CINSIYET, System.DateTime DTARIH, string ONTANI, int[] Test) {
            this.TestEkleAsync(Kadi, Ksifre, BARKOD, TCKIMLIK, ADI, SOYADI, CINSIYET, DTARIH, ONTANI, Test, null);
        }
        
        /// <remarks/>
        public void TestEkleAsync(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string ADI, string SOYADI, string CINSIYET, System.DateTime DTARIH, string ONTANI, int[] Test, object userState) {
            if ((this.TestEkleOperationCompleted == null)) {
                this.TestEkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestEkleOperationCompleted);
            }
            this.InvokeAsync("TestEkle", new object[] {
                        Kadi,
                        Ksifre,
                        BARKOD,
                        TCKIMLIK,
                        ADI,
                        SOYADI,
                        CINSIYET,
                        DTARIH,
                        ONTANI,
                        Test}, this.TestEkleOperationCompleted, userState);
        }
        
        private void OnTestEkleOperationCompleted(object arg) {
            if ((this.TestEkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestEkleCompleted(this, new TestEkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/TestGuncelle", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestGuncelle(string BARKOD, string Kadi, string Ksifre, int[] Test) {
            object[] results = this.Invoke("TestGuncelle", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre,
                        Test});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestGuncelleAsync(string BARKOD, string Kadi, string Ksifre, int[] Test) {
            this.TestGuncelleAsync(BARKOD, Kadi, Ksifre, Test, null);
        }
        
        /// <remarks/>
        public void TestGuncelleAsync(string BARKOD, string Kadi, string Ksifre, int[] Test, object userState) {
            if ((this.TestGuncelleOperationCompleted == null)) {
                this.TestGuncelleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestGuncelleOperationCompleted);
            }
            this.InvokeAsync("TestGuncelle", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre,
                        Test}, this.TestGuncelleOperationCompleted, userState);
        }
        
        private void OnTestGuncelleOperationCompleted(object arg) {
            if ((this.TestGuncelleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestGuncelleCompleted(this, new TestGuncelleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/BarkodSonucBilgisi", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucBilgisi[] BarkodSonucBilgisi(string BARKOD, string Kadi, string Ksifre) {
            object[] results = this.Invoke("BarkodSonucBilgisi", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre});
            return ((HastaSonucBilgisi[])(results[0]));
        }
        
        /// <remarks/>
        public void BarkodSonucBilgisiAsync(string BARKOD, string Kadi, string Ksifre) {
            this.BarkodSonucBilgisiAsync(BARKOD, Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void BarkodSonucBilgisiAsync(string BARKOD, string Kadi, string Ksifre, object userState) {
            if ((this.BarkodSonucBilgisiOperationCompleted == null)) {
                this.BarkodSonucBilgisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarkodSonucBilgisiOperationCompleted);
            }
            this.InvokeAsync("BarkodSonucBilgisi", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre}, this.BarkodSonucBilgisiOperationCompleted, userState);
        }
        
        private void OnBarkodSonucBilgisiOperationCompleted(object arg) {
            if ((this.BarkodSonucBilgisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarkodSonucBilgisiCompleted(this, new BarkodSonucBilgisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/TCSonucBilgisi", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucToplu[] TCSonucBilgisi(string Kadi, string Ksifre, string TCKIMLIK) {
            object[] results = this.Invoke("TCSonucBilgisi", new object[] {
                        Kadi,
                        Ksifre,
                        TCKIMLIK});
            return ((HastaSonucToplu[])(results[0]));
        }
        
        /// <remarks/>
        public void TCSonucBilgisiAsync(string Kadi, string Ksifre, string TCKIMLIK) {
            this.TCSonucBilgisiAsync(Kadi, Ksifre, TCKIMLIK, null);
        }
        
        /// <remarks/>
        public void TCSonucBilgisiAsync(string Kadi, string Ksifre, string TCKIMLIK, object userState) {
            if ((this.TCSonucBilgisiOperationCompleted == null)) {
                this.TCSonucBilgisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTCSonucBilgisiOperationCompleted);
            }
            this.InvokeAsync("TCSonucBilgisi", new object[] {
                        Kadi,
                        Ksifre,
                        TCKIMLIK}, this.TCSonucBilgisiOperationCompleted, userState);
        }
        
        private void OnTCSonucBilgisiOperationCompleted(object arg) {
            if ((this.TCSonucBilgisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TCSonucBilgisiCompleted(this, new TCSonucBilgisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/BarkodSil", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BarkodSil(string Kadi, string Ksifre, string barkod) {
            object[] results = this.Invoke("BarkodSil", new object[] {
                        Kadi,
                        Ksifre,
                        barkod});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BarkodSilAsync(string Kadi, string Ksifre, string barkod) {
            this.BarkodSilAsync(Kadi, Ksifre, barkod, null);
        }
        
        /// <remarks/>
        public void BarkodSilAsync(string Kadi, string Ksifre, string barkod, object userState) {
            if ((this.BarkodSilOperationCompleted == null)) {
                this.BarkodSilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarkodSilOperationCompleted);
            }
            this.InvokeAsync("BarkodSil", new object[] {
                        Kadi,
                        Ksifre,
                        barkod}, this.BarkodSilOperationCompleted, userState);
        }
        
        private void OnBarkodSilOperationCompleted(object arg) {
            if ((this.BarkodSilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarkodSilCompleted(this, new BarkodSilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esy.com.tr/DuyurulariGetir", RequestNamespace="http://www.esy.com.tr/", ResponseNamespace="http://www.esy.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Duyurular[] DuyurulariGetir(string Kadi, string Ksifre) {
            object[] results = this.Invoke("DuyurulariGetir", new object[] {
                        Kadi,
                        Ksifre});
            return ((Duyurular[])(results[0]));
        }
        
        /// <remarks/>
        public void DuyurulariGetirAsync(string Kadi, string Ksifre) {
            this.DuyurulariGetirAsync(Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void DuyurulariGetirAsync(string Kadi, string Ksifre, object userState) {
            if ((this.DuyurulariGetirOperationCompleted == null)) {
                this.DuyurulariGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDuyurulariGetirOperationCompleted);
            }
            this.InvokeAsync("DuyurulariGetir", new object[] {
                        Kadi,
                        Ksifre}, this.DuyurulariGetirOperationCompleted, userState);
        }
        
        private void OnDuyurulariGetirOperationCompleted(object arg) {
            if ((this.DuyurulariGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DuyurulariGetirCompleted(this, new DuyurulariGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }

        internal BarkodSonucBilgisiCompletedEventArgs[] BarkodSonucBilgisi(string p, string p_2)
        {
            throw new NotImplementedException();
        }

        internal BarkodSonucBilgisiCompletedEventArgs[] BarkodSonucBilgisi()
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class AktifTest {
        
        private string testGrupAdiField;
        
        private string butceKoduField;
        
        private string testAdiField;
        
        private string kisaAdField;
        
        private string testIDField;
        
        private string testOrnekTipiField;
        
        private string hataField;
        
        /// <remarks/>
        public string TestGrupAdi {
            get {
                return this.testGrupAdiField;
            }
            set {
                this.testGrupAdiField = value;
            }
        }
        
        /// <remarks/>
        public string ButceKodu {
            get {
                return this.butceKoduField;
            }
            set {
                this.butceKoduField = value;
            }
        }
        
        /// <remarks/>
        public string TestAdi {
            get {
                return this.testAdiField;
            }
            set {
                this.testAdiField = value;
            }
        }
        
        /// <remarks/>
        public string KisaAd {
            get {
                return this.kisaAdField;
            }
            set {
                this.kisaAdField = value;
            }
        }
        
        /// <remarks/>
        public string TestID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public string TestOrnekTipi {
            get {
                return this.testOrnekTipiField;
            }
            set {
                this.testOrnekTipiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class Duyurular {
        
        private string duyuruIDField;
        
        private string baslikField;
        
        private string icerikField;
        
        private string hataField;
        
        /// <remarks/>
        public string DuyuruID {
            get {
                return this.duyuruIDField;
            }
            set {
                this.duyuruIDField = value;
            }
        }
        
        /// <remarks/>
        public string Baslik {
            get {
                return this.baslikField;
            }
            set {
                this.baslikField = value;
            }
        }
        
        /// <remarks/>
        public string Icerik {
            get {
                return this.icerikField;
            }
            set {
                this.icerikField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class HastaSonucToplu {
        
        private HastaSonucBilgisi[] testSonuclariGenelField;
        
        private string hataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucBilgisi[] TestSonuclariGenel {
            get {
                return this.testSonuclariGenelField;
            }
            set {
                this.testSonuclariGenelField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class HastaSonucBilgisi {
        
        private string barkodField;
        
        private string tCKimlikNoField;
        
        private string adiSoyadiField;
        
        private string babaAdiField;
        
        private string dogumTarihiField;
        
        private string cinsiyetField;
        
        private string klinikAdiField;
        
        private string birimAdiField;
        
        private string kayitTarihiField;
        
        private string istemTarihiField;
        
        private string aciklamaField;
        
        private string aileHekimiAdiField;
        
        private string yasField;
        
        private string ornekAlmaTarihiField;
        
        private string hataField;
        
        private SonucBilgi[] testSonuclariField;
        
        /// <remarks/>
        public string Barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
        
        /// <remarks/>
        public string TCKimlikNo {
            get {
                return this.tCKimlikNoField;
            }
            set {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        public string AdiSoyadi {
            get {
                return this.adiSoyadiField;
            }
            set {
                this.adiSoyadiField = value;
            }
        }
        
        /// <remarks/>
        public string BabaAdi {
            get {
                return this.babaAdiField;
            }
            set {
                this.babaAdiField = value;
            }
        }
        
        /// <remarks/>
        public string DogumTarihi {
            get {
                return this.dogumTarihiField;
            }
            set {
                this.dogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Cinsiyet {
            get {
                return this.cinsiyetField;
            }
            set {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        public string KlinikAdi {
            get {
                return this.klinikAdiField;
            }
            set {
                this.klinikAdiField = value;
            }
        }
        
        /// <remarks/>
        public string BirimAdi {
            get {
                return this.birimAdiField;
            }
            set {
                this.birimAdiField = value;
            }
        }
        
        /// <remarks/>
        public string KayitTarihi {
            get {
                return this.kayitTarihiField;
            }
            set {
                this.kayitTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string istemTarihi {
            get {
                return this.istemTarihiField;
            }
            set {
                this.istemTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        public string AileHekimiAdi {
            get {
                return this.aileHekimiAdiField;
            }
            set {
                this.aileHekimiAdiField = value;
            }
        }
        
        /// <remarks/>
        public string Yas {
            get {
                return this.yasField;
            }
            set {
                this.yasField = value;
            }
        }
        
        /// <remarks/>
        public string OrnekAlmaTarihi {
            get {
                return this.ornekAlmaTarihiField;
            }
            set {
                this.ornekAlmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SonucBilgi[] TestSonuclari {
            get {
                return this.testSonuclariField;
            }
            set {
                this.testSonuclariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class SonucBilgi {
        
        private string testGrupAdiField;
        
        private string testAdiField;
        
        private string testParametreAdiField;
        
        private string testIDField;
        
        private string ornekTipiField;
        
        private string sonucField;
        
        private string sonucBirimField;
        
        private string sonucReferansField;
        
        private string sonucDurumField;
        
        private string sonucOnayTarihiField;
        
        private string sonucYorumField;
        
        private string sonucAciklamaField;
        
        /// <remarks/>
        public string TestGrupAdi {
            get {
                return this.testGrupAdiField;
            }
            set {
                this.testGrupAdiField = value;
            }
        }
        
        /// <remarks/>
        public string TestAdi {
            get {
                return this.testAdiField;
            }
            set {
                this.testAdiField = value;
            }
        }
        
        /// <remarks/>
        public string TestParametreAdi {
            get {
                return this.testParametreAdiField;
            }
            set {
                this.testParametreAdiField = value;
            }
        }
        
        /// <remarks/>
        public string TestID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public string OrnekTipi {
            get {
                return this.ornekTipiField;
            }
            set {
                this.ornekTipiField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string SonucBirim {
            get {
                return this.sonucBirimField;
            }
            set {
                this.sonucBirimField = value;
            }
        }
        
        /// <remarks/>
        public string SonucReferans {
            get {
                return this.sonucReferansField;
            }
            set {
                this.sonucReferansField = value;
            }
        }
        
        /// <remarks/>
        public string SonucDurum {
            get {
                return this.sonucDurumField;
            }
            set {
                this.sonucDurumField = value;
            }
        }
        
        /// <remarks/>
        public string SonucOnayTarihi {
            get {
                return this.sonucOnayTarihiField;
            }
            set {
                this.sonucOnayTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string SonucYorum {
            get {
                return this.sonucYorumField;
            }
            set {
                this.sonucYorumField = value;
            }
        }
        
        /// <remarks/>
        public string SonucAciklama {
            get {
                return this.sonucAciklamaField;
            }
            set {
                this.sonucAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TestEkleSonuc {
        
        private string sonucField;
        
        private string barkodField;
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AktifTestlerCompletedEventHandler(object sender, AktifTestlerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AktifTestlerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AktifTestlerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AktifTest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AktifTest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void TestEkleCompletedEventHandler(object sender, TestEkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestEkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestEkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEkleSonuc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEkleSonuc[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void TestGuncelleCompletedEventHandler(object sender, TestGuncelleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestGuncelleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestGuncelleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BarkodSonucBilgisiCompletedEventHandler(object sender, BarkodSonucBilgisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarkodSonucBilgisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarkodSonucBilgisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HastaSonucBilgisi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HastaSonucBilgisi[])(this.results[0]));
            }
        }

        public object BARKOD { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void TCSonucBilgisiCompletedEventHandler(object sender, TCSonucBilgisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TCSonucBilgisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TCSonucBilgisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HastaSonucToplu[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HastaSonucToplu[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BarkodSilCompletedEventHandler(object sender, BarkodSilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarkodSilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarkodSilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DuyurulariGetirCompletedEventHandler(object sender, DuyurulariGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DuyurulariGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DuyurulariGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Duyurular[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Duyurular[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591